clone_depth: 1
clone_folder: c:\projects\git-interactive-rebase-tool

# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: git-interactive-rebase-tool

  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: >-
        $Env:PATH += ';C:\msys64\mingw64\bin'
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target x86_64-pc-windows-msvc --release &&
      cargo test --target x86_64-pc-windows-msvc --release &&
      cargo run --target x86_64-pc-windows-msvc --release -- --version
    )

before_deploy:
  - cargo rustc --target x86_64-pc-windows-msvc --release --bin interactive-rebase-tool -- -C lto
  - ps: ci\before-deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: swMVdXZ3hh2gofrHrTJdXfsdddyngiC+nZieGWbu66PH1vGzPoYC1Rviy9/9kqFF
  description: ''
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+.*$/

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
