#[derive(Clone, Debug)]
pub(crate) struct KeyBindings {
	pub(crate) abort: String,
	pub(crate) action_break: String,
	pub(crate) action_drop: String,
	pub(crate) action_edit: String,
	pub(crate) action_fixup: String,
	pub(crate) action_pick: String,
	pub(crate) action_reword: String,
	pub(crate) action_squash: String,
	pub(crate) confirm_no: String,
	pub(crate) confirm_yes: String,
	pub(crate) edit: String,
	pub(crate) force_abort: String,
	pub(crate) force_rebase: String,
	pub(crate) help: String,
	pub(crate) move_down: String,
	pub(crate) move_down_step: String,
	pub(crate) move_left: String,
	pub(crate) move_right: String,
	pub(crate) move_selection_down: String,
	pub(crate) move_selection_up: String,
	pub(crate) move_up: String,
	pub(crate) move_up_step: String,
	pub(crate) open_in_external_editor: String,
	pub(crate) rebase: String,
	pub(crate) show_commit: String,
	pub(crate) toggle_visual_mode: String,
}
