.\" Manpage for interactive-rebase-tool.
.\" Contact dev@mitmaro.ca to correct errors or typos.
.TH INTERACTIVE\-REBASE 1 "02/02/2018" "v0.5.0" "Git Manual"
.SH NAME
interactive-rebase-tool \- an improved sequence editor for git
.SH SYNOPSIS
.nf
\fIinteractive-rebase-tool\fR <rebase-todo-filepath>
\fIinteractive-rebase-tool\fR --version | -v
.fi
.SH DESCRIPTION
Full feature terminal based sequence editor for git interactive rebase.
To configure git to use it by default for interactive rebasing
(i.e. with \fBgit rebase \-i\fR), use
.sp
.nf
\fIgit config\fR --global sequence.editor interactive-rebase-tool
.fi
.sp
Press ? during use for a summary of commands.
.SH SEE ALSO
git(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Tim Oram (dev@mitmaro.ca)
