pub fn get_input_short_name(input: &str) -> String {
	match input {
		"Backspace" => String::from("bs"),
		"Delete" => String::from("dl"),
		"Down" => String::from("dn"),
		"End" => String::from("end"),
		"Enter" => String::from("ent"),
		"Home" => String::from("hm"),
		"Insert" => String::from("ins"),
		"Left" => String::from("lf"),
		"Other" => String::from("ot"),
		"PageDown" => String::from("pdn"),
		"PageUp" => String::from("pup"),
		"Resize" => String::from("rz"),
		"Right" => String::from("rt"),
		"ShiftDelete" => String::from("sdl"),
		"ShiftEnd" => String::from("sed"),
		"ShiftDown" => String::from("sdw"),
		"ShiftHome" => String::from("shm"),
		"ShiftLeft" => String::from("slf"),
		"ShiftRight" => String::from("srt"),
		"ShiftTab" => String::from("Stb"),
		"ShiftUp" => String::from("sup"),
		"Tab" => String::from("tb"),
		"Up" => String::from("up"),
		_ => String::from(input),
	}
}
